"""Moving datetime tables to UTC

Revision ID: 41b0de0708de
Revises: 49efc90f5280
Create Date: 2023-09-20 12:48:36.329213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b0de0708de'
down_revision = '49efc90f5280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
