"""Change Group model to DateTime

Revision ID: 49efc90f5280
Revises: cf1c5921390c
Create Date: 2023-09-19 10:22:40.776901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49efc90f5280'
down_revision = 'cf1c5921390c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    op.add_column('group', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.drop_column('group', 'start_date')
    op.drop_column('group', 'end_date')
    op.drop_column('group', 'start_time')
    op.drop_column('group', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('group', 'end_datetime')
    op.drop_column('group', 'start_datetime')
    # ### end Alembic commands ###
