"""Add last_updated field to Expense

Revision ID: bd456ef5550b
Revises: 2fc32eaefe91
Create Date: 2023-05-23 20:46:02.269268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd456ef5550b'
down_revision = '2fc32eaefe91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
