"""Added schedule fields to Group model

Revision ID: cf1c5921390c
Revises: e5cadd6ed0bd
Create Date: 2023-09-14 20:08:56.253889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1c5921390c'
down_revision = 'e5cadd6ed0bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('group', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('group', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('group', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('group', sa.Column('location', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'location')
    op.drop_column('group', 'end_time')
    op.drop_column('group', 'start_time')
    op.drop_column('group', 'end_date')
    op.drop_column('group', 'start_date')
    # ### end Alembic commands ###
