"""Group members relation to Group

Revision ID: f1089ac749f2
Revises: de07bc347ff2
Create Date: 2023-07-04 16:39:59.049569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1089ac749f2'
down_revision = 'de07bc347ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
